_shared_job: &shared_job
    language: ruby
    allow_failures:
      rvm:
        - 2.5
        - 2.6
    before_install:
      - gem update --system
      - gem install bundler
      - git clone https://github.com/bitcoin-dot-org/Bitcoin.org
      - git clone https://github.com/bitcoin-dot-org/developer.bitcoin.org
      - git clone https://github.com/bitcoin-core/bitcoincore.org
    install: echo "shared install config"
    after_install: echo "shared after_install config"
    env:
      global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - BITCOIN_ORG=https://github.com/bitcoin-dot-org/Bitcoin.org
      - DEVELOPER_BITCOIN_ORG=https://github.com/bitcoin-dot-org/developer.bitcoin.org
      - BITCCOINCORE_ORG=https://github.com/bitcoin-core/bitcoincore.org
    branches:
      only:
        - master
    notifications:
      email:
        - admin@bitcoincore.dev
    cache: bundler

jobs:
  include:
  - name: cibuild
    <<: *shared_job
    install: echo "shared install config"
    script: "script/cibuild"

  - name: cibuild-bitcoin-org
    <<: *shared_job
    install: echo "shared install config"
    script: "script/cibuild-bitcoin-org"

  - name: cibuild-developer-bitcoin-org
    <<: *shared_job
    install: echo "shared install config"
    script: "script/cibuild-developer-bitcoin-org"

  - name: cibuild-bitcoincore-org
    <<: *shared_job
    install: echo "shared install config"
    script: "script/cibuild-bitcoincore-org"

